In [1]:
import numpy as np
arr1 = np.array([1,2,3])
print(arr1)

[1 2 3]


In [2]:
arr1[2]

3

In [3]:
arr1[2]=5
arr1

array([1, 2, 5])

In [4]:
arr2 = np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [6]:
print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [7]:
print(arr2[0][2])
print(arr2[0,2])
print(arr2[0,-1])
print(arr2[-1,0])

3
3
3
4


In [8]:
arr3 = np.array(['India','china','USA','Mexico'])
print(arr3)

['India' 'china' 'USA' 'Mexico']


In [10]:
arr = np.arange(0,20,2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [11]:
arr = np.linspace(0,10,20)
print(arr)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [12]:
arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[0.07983624 0.7981555  0.42236386 0.43108355 0.79397975 0.28915909
 0.71906835 0.39481808 0.8764482  0.26563453]


[[0.74718422 0.7951927  0.76723368 0.09233767]
 [0.70914598 0.03536911 0.67648421 0.86870353]
 [0.8222669  0.89949395 0.19067862 0.04611628]]


In [13]:
print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [14]:
arr = [0,1,2]
print(np.repeat(arr,3))

[0 0 0 1 1 1 2 2 2]


In [16]:
arr = [0,1,2]
print(np.tile(arr,3))

[0 1 2 0 1 2 0 1 2]


In [17]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [18]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
arr = np.random.rand(5,5)
print(arr)

[[0.4180819  0.8988013  0.86526809 0.84981448 0.52946441]
 [0.4184945  0.01025392 0.62566908 0.59800139 0.79216932]
 [0.85561835 0.38030713 0.86120616 0.92654565 0.44478632]
 [0.55271687 0.47201267 0.68707304 0.72722748 0.07288412]
 [0.52049433 0.55882971 0.48716724 0.79417256 0.34318653]]


In [20]:
print(np.sum(arr,axis=0))

[2.76540595 2.32020472 3.5263836  3.89576156 2.1824907 ]


In [21]:
print(np.sum(arr, axis=1))

[3.56143018 2.44458821 3.4684636  2.51191418 2.70385036]


In [22]:
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))

0.5876098613775733
0.55882971170861
0.23931754857267695
0.05727288905483559


In [23]:
arr = np.random.rand(5,5)
print(arr)

[[0.70217596 0.35059505 0.53200855 0.40189122 0.95780938]
 [0.90965926 0.97290876 0.35688631 0.84553529 0.59069232]
 [0.13608391 0.65719084 0.8216988  0.01323374 0.30654824]
 [0.67196979 0.8844034  0.50893513 0.99688796 0.75994561]
 [0.13041547 0.19418778 0.93261102 0.71655304 0.44713759]]


In [24]:
print(np.sort(arr, axis=1))

[[0.35059505 0.40189122 0.53200855 0.70217596 0.95780938]
 [0.35688631 0.59069232 0.84553529 0.90965926 0.97290876]
 [0.01323374 0.13608391 0.30654824 0.65719084 0.8216988 ]
 [0.50893513 0.67196979 0.75994561 0.8844034  0.99688796]
 [0.13041547 0.19418778 0.44713759 0.71655304 0.93261102]]


In [25]:
arr = np.array([4,5,6,7])

In [26]:
arr1 = np.append(arr,8)
arr1

array([4, 5, 6, 7, 8])

In [27]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [28]:
arr2 = np.array([4,5,6,7,9,10,11])
print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [29]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [30]:
cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [31]:
cat = np.concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]
